In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

from sklearn.feature_extraction.text import CountVectorizer
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Embedding, LSTM, SpatialDropout1D, Conv1D, MaxPooling1D, Dropout, Bidirectional
from keras.utils.vis_utils import plot_model
from sklearn.model_selection import train_test_split
from keras.utils.np_utils import to_categorical

# format pandas output
pd.set_option('display.max_columns', None)  # Show all columns
import re

# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

In [2]:
"""Load data"""
data = pd.read_csv('../input/Sentiment.csv')
# check data
data.head()

id               candidate  candidate_confidence relevant_yn  \
0   1  No candidate mentioned                   1.0         yes   
1   2            Scott Walker                   1.0         yes   
2   3  No candidate mentioned                   1.0         yes   
3   4  No candidate mentioned                   1.0         yes   
4   5            Donald Trump                   1.0         yes   

   relevant_yn_confidence sentiment  sentiment_confidence     subject_matter  \
0                     1.0   Neutral                0.6578  None of the above   
1                     1.0  Positive                0.6333  None of the above   
2                     1.0   Neutral                0.6629  None of the above   
3                     1.0  Positive                1.0000  None of the above   
4                     1.0  Positive                0.7045  None of the above   

   subject_matter_confidence candidate_gold             name relevant_yn_gold  \
0                     1.0000            NaN       I_Am_Kenzi              NaN   
1                     1.0000            NaN    PeacefulQuest              NaN   
2                     0.6629            NaN    PussssyCroook              NaN   
3                     0.7039            NaN  MattFromTexas31              NaN   
4                     1.0000            NaN       sharonDay5              NaN   

   retweet_count sentiment_gold subject_matter_gold  \
0              5            NaN                 NaN   
1             26            NaN                 NaN   
2             27            NaN                 NaN   
3            138            NaN                 NaN   
4            156            NaN                 NaN   

                                                text tweet_coord  \
0  RT @NancyLeeGrahn: How did everyone feel about...         NaN   
1  RT @ScottWalker: Didn't catch the full #GOPdeb...         NaN   
2  RT @TJMShow: No mention of Tamir Rice and the ...         NaN   
3  RT @RobGeorge: That Carly Fiorina is trending ...         NaN   
4  RT @DanScavino: #GOPDebate w/ @realDonaldTrump...         NaN   

               tweet_created            tweet_id tweet_location  \
0  2015-08-07 09:54:46 -0700  629697200650592256            NaN   
1  2015-08-07 09:54:46 -0700  629697199560069120            NaN   
2  2015-08-07 09:54:46 -0700  629697199312482304            NaN   
3  2015-08-07 09:54:45 -0700  629697197118861312          Texas   
4  2015-08-07 09:54:45 -0700  629697196967903232            NaN   

                user_timezone  
0                       Quito  
1                         NaN  
2                         NaN  
3  Central Time (US & Canada)  
4                     Arizona

In [3]:
"""Clean data"""
# Keeping only the necessary columns
data = data[['text','sentiment']]
# keeping sentiment only Positive and Negative, remove Neutral
data = data[data.sentiment != "Neutral"]
data.head()

text sentiment
1  RT @ScottWalker: Didn't catch the full #GOPdeb...  Positive
3  RT @RobGeorge: That Carly Fiorina is trending ...  Positive
4  RT @DanScavino: #GOPDebate w/ @realDonaldTrump...  Positive
5  RT @GregAbbott_TX: @TedCruz: "On my first day ...  Positive
6  RT @warriorwoman91: I liked her and was happy ...  Negative

In [4]:
"""Natural language processing (NLP)"""
data['text'] = data['text'].apply(lambda a: a.lower())  # Lower words
data['text'] = data['text'].apply((lambda a: re.sub('[^a-zA-z0-9\s]','',a)))    # Only keep words and number

# Print the sum of Positive and Negative
print(data[ data['sentiment'] == 'Positive'].shape[0])
print(data[ data['sentiment'] == 'Negative'].shape[0])

# remove 'rt'
for idx,row in data.iterrows():
    row[0] = row[0].replace('rt',' ')

# Tokenize sentence
max_features = 2000
tokenizer = Tokenizer(num_words=max_features, split=' ')
tokenizer.fit_on_texts(data['text'].values)
X = tokenizer.texts_to_sequences(data['text'].values)
# Transfer into a 2D Numpy array
X = pad_sequences(X)
print(X)

2236
8493
[[   0    0    0 ... 1324 1409  743]
 [   0    0    0 ...  233  724   17]
 [   0    0    0 ...  207  371  670]
 ...
 [   0    0    0 ...   72   65    3]
 [   0    0    0 ... 1022 1423   74]
 [   0    0    0 ...  197    3  723]]


In [5]:
"""Build model"""
embed_dim = 128
lstm_out = 196

# Fourth Version
# model = Sequential()
# model.add(Embedding(max_features, 128, input_length=X.shape[1]))
# model.add(Bidirectional(LSTM(64)))
# model.add(Dropout(0.5))
# model.add(Dense(2, activation='sigmoid'))
# model.compile(loss = 'categorical_crossentropy', optimizer='adam',metrics = ['accuracy'])
# print(model.summary())

# Third Version
model = Sequential()
model.add(Embedding(max_features, embed_dim,input_length = X.shape[1]))
model.add(Dropout(0.4))
model.add(LSTM(lstm_out, dropout=0.2, recurrent_dropout=0.2))
model.add(Dropout(0.4))
model.add(Dense(32,activation='relu'))
model.add(Dropout(0.4))
model.add(Dense(2,activation='sigmoid'))
model.compile(loss = 'categorical_crossentropy', optimizer='adam',metrics = ['accuracy'])
print(model.summary())


# Second Version
# model = Sequential()
# model.add(Embedding(max_features, embed_dim,input_length = X.shape[1]))
# model.add(Conv1D(filters=32, kernel_size=3, padding='same', activation='relu'))
# model.add(MaxPooling1D(pool_size=2))
# model.add(Conv1D(filters=32, kernel_size=3, padding='same', activation='relu'))
# model.add(MaxPooling1D(pool_size=2))
# model.add(LSTM(lstm_out, dropout=0.2, recurrent_dropout=0.2))
# model.add(Dense(2,activation='softmax'))
# model.compile(loss = 'categorical_crossentropy', optimizer='adam',metrics = ['accuracy'])
# print(model.summary())

# First Version
# model = Sequential()
# model.add(Embedding(max_features, embed_dim,input_length = X.shape[1]))
# model.add(SpatialDropout1D(0.4))
# model.add(LSTM(lstm_out, dropout=0.2, recurrent_dropout=0.2))
# model.add(Dense(2,activation='softmax'))
# model.compile(loss = 'categorical_crossentropy', optimizer='adam',metrics = ['accuracy'])
# print(model.summary())
# plot_model(model, to_file='model.png')

2021-09-30 14:30:46.349061: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 28, 128)           256000    
_________________________________________________________________
dropout (Dropout)            (None, 28, 128)           0         
_________________________________________________________________
lstm (LSTM)                  (None, 196)               254800    
_________________________________________________________________
dropout_1 (Dropout)          (None, 196)               0         
_________________________________________________________________
dense (Dense)                (None, 32)                6304      
_________________________________________________________________
dropout_2 (Dropout)          (None, 32)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 6

In [6]:
"""Split dataset to train and test"""
# Convert categorical variable into dummy/indicator variables.
Y = pd.get_dummies(data['sentiment']).values
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.33, random_state = 42)
print(X_train.shape,Y_train.shape)
print(X_test.shape,Y_test.shape)

(7188, 28) (7188, 2)
(3541, 28) (3541, 2)


In [7]:
"""Train model"""
batch_size = 32
model.fit(X_train, Y_train, epochs=7, batch_size=batch_size, verbose=2)

Epoch 1/7


2021-09-30 14:30:46.667193: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


225/225 - 36s - loss: 0.4445 - accuracy: 0.8148
Epoch 2/7
225/225 - 29s - loss: 0.3267 - accuracy: 0.8692
Epoch 3/7
225/225 - 31s - loss: 0.2878 - accuracy: 0.8837
Epoch 4/7
225/225 - 29s - loss: 0.2492 - accuracy: 0.9018
Epoch 5/7
225/225 - 33s - loss: 0.2260 - accuracy: 0.9092
Epoch 6/7
225/225 - 34s - loss: 0.2035 - accuracy: 0.9172
Epoch 7/7
225/225 - 31s - loss: 0.1800 - accuracy: 0.9275


In [8]:
# Cal F1 score and acc in test dataset
validation_size = 1500

# Validate dataset : last 1500
X_validate = X_test[-validation_size:]
Y_validate = Y_test[-validation_size:]
# Test dataset : others
X_test = X_test[:-validation_size]
Y_test = Y_test[:-validation_size]
score,acc = model.evaluate(X_test, Y_test, verbose=2, batch_size=batch_size)
print("score: %.2f" % score)
print("acc: %.2f" % acc)

64/64 - 2s - loss: 0.4878 - accuracy: 0.8319
score: 0.49
acc: 0.83


In [9]:
pos_cnt, neg_cnt, pos_correct, neg_correct = 0, 0, 0, 0

for x in range(len(X_validate)):
    result = model.predict(X_validate[x].reshape(1, X_test.shape[1]), batch_size=1, verbose=2)[0]
    if np.argmax(result) == np.argmax(Y_validate[x]):
        if np.argmax(Y_validate[x]) == 0:
            neg_correct += 1
        else:
            pos_correct += 1
    if np.argmax(Y_validate[x]) == 0:
        neg_cnt += 1
    else:
        pos_cnt += 1

print("pos_acc", pos_correct/pos_cnt*100, "%")
print("neg_acc", neg_correct/neg_cnt*100, "%")

1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1/1 - 0s
1

In [10]:
twt = ['Meetings: Because none of us is as dumb as all of us.']
#vectorizing the tweet by the pre-fitted tokenizer instance
twt = tokenizer.texts_to_sequences(twt)
#padding the tweet to have exactly the same shape as `embedding_2` input
twt = pad_sequences(twt, maxlen=28, dtype='int32', value=0)
print(twt)
sentiment = model.predict(twt, batch_size=1, verbose = 2)[0]
if np.argmax(sentiment) == 0:
    print("negative")
elif np.argmax(sentiment) == 1:
    print("positive")


[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0  206  633    6  150    5   55 1055   55   46    6  150]]
1/1 - 0s
negative
